### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ghbrown** [Jrostaggs97/Jrostaggs97.github.io#1]
What is even happening here? 404, no `index.html`, just a big pile of bungled bundles...

Perhaps try following the [the trivial instructions](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll). If you are feeling discouraged [this tutorial](https://www.youtube.com/watch?v=dQw4w9WgXcQ) could also be useful.

**Comment by Jrostaggs97** [comment]
Dear concerned user, 

We thank you for bringing this to our attention! We have followed along both with the trivial set of instructions and the additional tutorial provided to resolve this issue.
